name: checks-impure
on:
  pull_request:
  push:
    branches: main
jobs:
  test:
    if: ${{ github.actor != 'clan-bot' }}
    runs-on: nix
    steps:
      - uses: actions/checkout@v3
      - run: nix run .#impure-checks
